In [75]:
import numpy as np
from pprint import pprint

# Needleman  - Wunsch

Implementación del algoritmo NW. Los valores para gap, msm y mth se especifican a continuación.
La matriz de comparación $\delta$ se usará la que se presenta a continuación.

| $\delta$ | a | b |
|-- |---- |--- |
| a | $\epsilon$ | $\mu$  | 
| b | $\mu$ | $\epsilon$ | 


In [97]:
mu    = -1  #mismatch
eps   =  2  #match
sigma = -2  #gap

def delta(u,v,msm=mu,mth=eps):
    if(u==v):
        return mth
    else:
        return msm
#ejemplo
pprint(delta('g','g'))
pprint(delta('g','t'))

2
-1


La matriz de scores $S$ se llena con la funcion $s_{i,j}$ como se presenta a continuación



\begin{align}
S_{i,j} (u_i,v_j) & = \max \left \{ \begin{array} {ll}
                                    S_{i-1,j} - \sigma \\
                                    S_{i,j-1} - \sigma \\
                                    S_{i-1,j-1} + \delta (u_i,v_j) \\
                        \end{array} \right .
\end{align}



In [98]:
def entrada(S,i,j,V,U,mu=mu, eps=eps,sigma=sigma,delta=delta):
    arriba    = S[i-1,  j] + sigma
    izquierda = S[i  ,j-1] + sigma
    u,v       = V[i-1], U[j-1]
    valdelta  = delta(u,v, msm=mu, mth=eps)
    match     = S[i-1,j-1] + valdelta
    ## entrada de la matriz
    l         = [arriba, izquierda, match]
    ## valor de donde viene el maximo
    mx        = max(l)
    cod       = sum([(i+1) for i in range(len(l)) if l[i]==mx])
    return max(l), cod



Para esto requerimos hacer un par de matrices, a saber S y B

In [99]:
V = 'CTAA'  # |V| = n
U = 'CTAA'   # |U| = m
S = np.zeros((len(V)+1,len(U)+1))
B = np.zeros_like(S)
pprint(S)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])


El algoritmo pide llenar la primer fila 

1)
```
for i=1..|V|
    S[i,0] = S[i-1,0] - s
```

2)
```
for j=1..|V|
    S[0,j] = S[0,j-1] - s
```


In [100]:
for i in range(1,len(V)+1):
    S[i,0] = S[i-1,0] - eps
for j in range(1,len(U)+1):
    S[0,j] = S[0,j-1] - eps
pprint(S)

array([[ 0., -2., -4., -6., -8.],
       [-2.,  0.,  0.,  0.,  0.],
       [-4.,  0.,  0.,  0.,  0.],
       [-6.,  0.,  0.,  0.,  0.],
       [-8.,  0.,  0.,  0.,  0.]])


Desupués rellenamos el contenido de la matriz

In [101]:
for i in range(1,len(V)+1):
    for j in range(1,len(U)+1):
        S[i,j], B[i,j] = entrada(S,i,j,V,U)

In [102]:
pprint(S)

array([[ 0., -2., -4., -6., -8.],
       [-2.,  2.,  0., -2., -4.],
       [-4.,  0.,  4.,  2.,  0.],
       [-6., -2.,  2.,  6.,  4.],
       [-8., -4.,  0.,  4.,  8.]])


In [103]:
pprint(B)

array([[0., 0., 0., 0., 0.],
       [0., 3., 2., 2., 2.],
       [0., 1., 3., 2., 2.],
       [0., 1., 1., 3., 5.],
       [0., 1., 1., 4., 3.]])


In [89]:
np.diag(S)

array([0., 2., 4., 6.])